"""Build a distributable of data_acquisition.

    python build.py             one-folder build  ->  dist/DataAcquisition/
                                zipped as dist/DataAcquisition-v<VER>-<os>.zip
    python build.py --onefile   single DataAcquisition.exe  (+ zipped)
    python build.py --no-zip    skip the zip step

Prereqs:   pip install -r requirements.txt      (pyinstaller is in there)

Hand the resulting .zip to lab users; they extract it and run
DataAcquisition(.exe).  Nothing else to install.  See DISTRIBUTION.md.
"""
from __future__ import annotations

import argparse
import os
import platform
import shutil
import subprocess
import sys
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from app import VERSION  # noqa: E402

OSTAG = {"Windows": "win64", "Darwin": "macos", "Linux": "linux"}.get(
    platform.system(), platform.system().lower())
EXE = "DataAcquisition.exe" if platform.system() == "Windows" else "DataAcquisition"


def _run(cmd):
    print("$", " ".join(cmd))
    subprocess.check_call(cmd, cwd=HERE)


def _clean():
    for d in ("build", "dist"):
        p = os.path.join(HERE, d)
        if os.path.isdir(p):
            shutil.rmtree(p)


_VERINFO_TMPL = """\
# PyInstaller Windows version resource for DataAcquisition.exe
# AUTO-GENERATED by build.py from VERSION in app.py -- do not hand-edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({nums}),
    prodvers=({nums}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', 'UniMelb Mech Eng - cryogenic SSN group'),
         StringStruct('FileDescription', 'data_acquisition - plot digitizer'),
         StringStruct('FileVersion', '{v}'),
         StringStruct('InternalName', 'DataAcquisition'),
         StringStruct('LegalCopyright', ''),
         StringStruct('OriginalFilename', 'DataAcquisition.exe'),
         StringStruct('ProductName', 'data_acquisition'),
         StringStruct('ProductVersion', '{v}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def _sync_version_files():
    """Regenerate VERSION and file_version_info.txt from app.VERSION.

    app.py's ``VERSION`` is the single source of truth; this keeps the Windows
    version resource and the plain VERSION file in step so a release is a
    one-line bump.
    """
    v = VERSION.strip().lstrip("vV")
    bits = (v.split("-")[0].split(".") + ["0", "0", "0"])[:4]
    nums = ", ".join(str(int(x) if x.isdigit() else 0) for x in bits)
    with open(os.path.join(HERE, "VERSION"), "w", encoding="utf-8", newline="\n") as f:
        f.write(v + "\n")
    with open(os.path.join(HERE, "file_version_info.txt"), "w",
              encoding="utf-8", newline="\n") as f:
        f.write(_VERINFO_TMPL.format(nums=nums, v=v))
    print(f"  version files synced to {v}")


def _zip_dir(folder, out):
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        for root, _, files in os.walk(folder):
            for f in files:
                fp = os.path.join(root, f)
                arc = os.path.join("DataAcquisition",
                                   os.path.relpath(fp, folder))
                z.write(fp, arc)
    print("  zipped ->", out, f"({os.path.getsize(out) / 1e6:.1f} MB)")


def _zip_files(paths, out):
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        for p in paths:
            if os.path.exists(p):
                z.write(p, os.path.basename(p))
    print("  zipped ->", out, f"({os.path.getsize(out) / 1e6:.1f} MB)")


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--onefile", action="store_true",
                    help="single self-extracting .exe instead of a folder")
    ap.add_argument("--no-zip", action="store_true")
    args = ap.parse_args()

    _clean()
    _sync_version_files()
    dist = os.path.join(HERE, "dist")

    if args.onefile:
        _run([sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean",
              "--onefile", "--windowed", "--name", "DataAcquisition",
              "--icon", os.path.join("assets", "icon.ico"),
              "--add-data", os.path.join("assets", "icon.ico") + os.pathsep + "assets",
              "--version-file", "file_version_info.txt",
              "--exclude-module", "scipy", "--exclude-module", "matplotlib",
              "app.py"])
        payload = os.path.join(dist, EXE)
        if not os.path.exists(payload):
            sys.exit("build failed: " + payload + " not produced")
        print("  exe ->", payload, f"({os.path.getsize(payload) / 1e6:.1f} MB)")
        if not args.no_zip:
            _zip_files([payload, os.path.join(HERE, "DISTRIBUTION.md")],
                       os.path.join(dist, f"DataAcquisition-v{VERSION}-{OSTAG}-onefile.zip"))
    else:
        _run([sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean",
              "DataAcquisition.spec"])
        folder = os.path.join(dist, "DataAcquisition")
        if not os.path.isdir(folder):
            sys.exit("build failed: " + folder + " not produced")
        shutil.copy(os.path.join(HERE, "DISTRIBUTION.md"),
                    os.path.join(folder, "DISTRIBUTION.md"))
        if not args.no_zip:
            _zip_dir(folder, os.path.join(
                dist, f"DataAcquisition-v{VERSION}-{OSTAG}.zip"))

    print("\nDone.  Contents of dist/:")
    for f in sorted(os.listdir(dist)):
        print("  ", f)


if __name__ == "__main__":
    main()
